version: '3.8'

services:
  nuxt:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: front
    ports:
      - '3000:3000'
    environment:
      - HOST=0.0.0.0
    volumes:
      - ../:/app
    command: 'npm run dev'
    networks:
      - my-network

networks:
  my-network:
